### ISSUE TITLE
Running `zkstack chain init` failed with error: multiple fields provided for oneof 'config' at line 399 column 3

### ISSUE THREAD

**Issue by cstrangedk** [matter-labs/zksync-era#3545]
#### 📝 Description

Running `zkstack chain init` failed with error: multiple fields provided for oneof 'config' at line 399 column 3.

#### 🔄 Reproduction Steps

`zkstack chain init`

Parameter selections:
```
Do you want to deploy Paymaster contract?
│  Yes
│
◇  What is the RPC URL of the L1 network?
│  http://127.0.0.1:8545
│
◇  Select the Validium type
│  Avail
│
◇  Avail client type
│  FullClient
│
◇  Avail API node URL
│  wss://turing-rpc.avail.so/ws
│
◇  Avail app id
│  208
│
◇  Avail finality state
│  InBlock
│
◇  Attestation bridge API URL
│  https://turing-bridge-api.avail.so/
│
◇  Avail API timeout in milliseconds
│  7200000
... (rest omitted)
```

#### 🤔 Expected Behavior

Command success, and database initialization in postgres container

#### 😯 Current Behavior

Command fails with error message

Output of general.yaml:

```
...(omitted)
da_client:
  avail:                                  # line 399
    bridge_api_url: https://turing-bridge-api.avail.so/
    full_client:
      api_node_url: wss://turing-rpc.avail.so/ws
      app_id: 208
      finality_state: InBlock
    timeout_ms: 7200000
  no_da: {}
...
```

#### 🖥️ Environment

NixOS VM, 

```
zkstack --version
zkstack v0.1.2-cd21c9ea
Branch: master
Submodules:
  - contracts: 16dedf6d77695ce00f81fce35a3066381b97fca1
Build timestamp: 2025-01-28 05:00:32
```

#### 📋 Additional Context

None

#### 📎 Log Output

```
●  Initializing chain
│
■  Failed to create portal config
│
▲    0: da_client: multiple fields provided for oneof 'config' at line 399 column 3
│
└  Failed to run command
```
