### ISSUE TITLE
Problems with eth_tx_manager on custom network

### ISSUE THREAD

**Issue by Borman322** [matter-labs/zksync-era#4237]
**Title:** `eth_tx_manager` panics with `WrongFeeProvided` using zkSync-recommended fee config. I'm using zkstack v28.6.0

**Description:**

When running `zksync_server` with the following recommended configuration:

```yaml
sender:
  max_acceptable_priority_fee_in_gwei: 100000000000
  ...
gas_adjuster:
  default_priority_fee_per_gas: 1000000000
  ...
base_token_adjuster:
  max_acceptable_priority_fee_in_gwei: 100000000000
```

the server crashes with:

```
Task eth_tx_manager panicked: Failed to sign transaction: WrongFeeProvided(6346864969358770176, 17179869184000000000)
```

This happens consistently at startup.

The issue appears to originate from an inconsistency between the computed transaction fee and the one passed into the signing step.

Please investigate.
